sudo: required

language: java

branches:
  only:
    - master

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk7
    - jdk: openjdk6
      env: COVERALLS=yes
  fast_finish: true

before_script:
  - git clone -b libpcap-1.7.4 git://github.com/the-tcpdump-group/libpcap.git libpcap
  - cd libpcap
  - ./configure
  - make && sudo make install
  - cd ..

script:
  sudo /usr/local/maven/bin/mvn -Dorg.pcap4j.core.pcapLibName=/usr/local/lib/libpcap.so test -B

after_success:
    - if [ "${COVERALLS}" = "yes"  ]; then mvn -Dorg.pcap4j.core.test.enableTimestampPrecisionTests=true -P test-coverage clean package coveralls:report; fi

notifications:
  email:
    recipients:
      - kaitoy@pcap4j.org
    on_success: change
    on_failure: always
