sudo: required

language: java

branches:
  only:
    - master

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: oraclejdk7
    - jdk: openjdk6
      env: COVERALLS=yes
  fast_finish: true

before_script:
  - git clone -b libpcap-1.7.4 git://github.com/the-tcpdump-group/libpcap.git libpcap
  - cd libpcap
  - ./configure
  - make && sudo make install
  - export LD_LIBRARY_PATH=/usr/local/lib
  - sudo apt-get update -qq
  - sudo apt-get install -qq libcap2-bin
  - sudo setcap cap_net_raw,cap_net_admin=eip `readlink -f $MAVEN_HOME/bin/mvn`
  - cd ..

after_success:
    - if [ "${COVERALLS}" = "yes"  ]; then mvn -Dorg.pcap4j.core.test.enableTimestampPrecisionTests=true -P test-coverage clean package coveralls:report; fi

notifications:
  email:
    recipients:
      - kaitoy@pcap4j.org
    on_success: change
    on_failure: always
