#---------------------------------#
#      general configuration      #
#---------------------------------#
 
# version format
version: 1.5.0.{build}-{branch}

# branches to build
branches:
  # whitelist
  only:
    - master

  # blacklist
  except:
    - gh-pages

# Do not build on tags
skip_tags: true

# Skipping commits with particular message or from user
skip_commits:
  message: /\[maven-release-plugin\]/

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Operating system (build VM template)
os: unstable

# fetch repository as zip archive
shallow_clone: false

# environment variables
environment:
  SONATYPE_NEXUS_USERNAME:
    secure: DDwS0DjK9j/d79DuAlJy3A==
  SONATYPE_NEXUS_PASSWORD:
    secure: mr5kcUXHVYPmF+7bXPi2Ow==

# scripts that run after cloning repository
install:
  # Install WinPcap
  - cmd: choco install -y winpcap
  # Install Maven
  - cmd: choco install -y maven
  # Get the Maven bin directory path
  - ps: $env:MAVEN_BIN_PATH = [Environment]::GetEnvironmentVariable('M2', 'User')
  - cmd: echo %MAVEN_BIN_PATH%
  # Set JAVA_HOME
  - ps: $env:PATH -match '[;|^][^;]*\\jdk[^;]*[;|\\Z]'
  - ps: $env:JAVA_HOME = $matches[0] -replace ';|\\bin', ''
  - cmd: echo %JAVA_HOME%

#---------------------------------#
#       build configuration       #
#---------------------------------#
 
# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# scripts to run before build
before_build:
  - cmd: if not exist %userprofile%\.m2 (mkdir %userprofile%\.m2)
  - cmd: copy /y mvn\settings.xml %userprofile%\.m2

build_script:
  - cmd: call "%MAVEN_BIN_PATH%\mvn" -Djna.nosys=true deploy

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test: off

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

deploy: off

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:

  - provider: Email
    to: kaitoy@pcap4j.org
    on_build_success: false
    on_build_failure: true

